sudo: false
dist: trusty
language: node_js
node_js:
# - lts/* enable after next LTS release; v6 <= 7.7.1 (package minimum)
- node
cache:
  yarn: true
  directories:
    - node_modules

install: yarn install
script: yarn test
